#Stage1 to build a frontend

FROM maven:3.9.9-eclipse-temurin-21-alpine AS build

WORKDIR /app

COPY pom.xml ./

RUN mvn dependency:go-offline

COPY src/ ./src

RUN mvn package -DskipTests



#Stage2 : serving with nginx

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/stationary*.jar app.jar

ENTRYPOINT ["java"]

CMD ["-jar","app.jar"]  