#Stage1 to build a frontend

FROM node:18 AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

#Stage2 : serving with nginx

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=build /app/build .

EXPOSE 80

CMD ["nginx","-g","daemon off;"]